const dataCandidate = [
  {
    id: 1,
    fullName: 'Nguyen Van A',
    dob: '1995-05-10',
    gender: 'Nam',
    region: 'Miền Bắc',
    phone: '0901234567',
    email: 'vana1@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Ba Đình',
    address: '123 Đội Cấn',
    avatarUrl: '',
  },
  {
    id: 2,
    fullName: 'Tran Thi B',
    dob: '1998-08-21',
    gender: 'Nữ',
    region: 'Miền Nam',
    phone: '0912345678',
    email: 'thib2@gmail.com',
    country: 'Việt Nam',
    city: 'TP.HCM',
    ward: 'Quận 1',
    address: '45 Nguyễn Huệ',
    avatarUrl: '',
  },
  {
    id: 3,
    fullName: 'Le Van C',
    dob: '1992-03-15',
    gender: 'Nam',
    region: 'Miền Trung',
    phone: '0923456789',
    email: 'vanc3@gmail.com',
    country: 'Việt Nam',
    city: 'Đà Nẵng',
    ward: 'Hải Châu',
    address: '78 Trần Phú',
    avatarUrl: '',
  },
  {
    id: 4,
    fullName: 'Pham Thi D',
    dob: '1990-11-01',
    gender: 'Nữ',
    region: 'Miền Bắc',
    phone: '0934567890',
    email: 'thid4@gmail.com',
    country: 'Việt Nam',
    city: 'Hải Phòng',
    ward: 'Lê Chân',
    address: '12 Lạch Tray',
    avatarUrl: '',
  },
  {
    id: 5,
    fullName: 'Hoang Van E',
    dob: '1997-06-18',
    gender: 'Nam',
    region: 'Miền Nam',
    phone: '0945678901',
    email: 'vane5@gmail.com',
    country: 'Việt Nam',
    city: 'Cần Thơ',
    ward: 'Ninh Kiều',
    address: '56 30/4',
    avatarUrl: '',
  },
  {
    id: 6,
    fullName: 'Vo Thi F',
    dob: '1993-09-12',
    gender: 'Nữ',
    region: 'Miền Trung',
    phone: '0956789012',
    email: 'thif6@gmail.com',
    country: 'Việt Nam',
    city: 'Huế',
    ward: 'Phú Nhuận',
    address: '22 Hùng Vương',
    avatarUrl: '',
  },
  {
    id: 7,
    fullName: 'Dang Van G',
    dob: '1999-02-25',
    gender: 'Nam',
    region: 'Miền Bắc',
    phone: '0967890123',
    email: 'vang7@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Cầu Giấy',
    address: '89 Xuân Thủy',
    avatarUrl: '',
  },
  {
    id: 8,
    fullName: 'Bui Thi H',
    dob: '1994-12-30',
    gender: 'Nữ',
    region: 'Miền Nam',
    phone: '0978901234',
    email: 'thih8@gmail.com',
    country: 'Việt Nam',
    city: 'TP.HCM',
    ward: 'Quận 3',
    address: '15 Võ Văn Tần',
    avatarUrl: '',
  },
  {
    id: 9,
    fullName: 'Do Van I',
    dob: '1991-04-04',
    gender: 'Nam',
    region: 'Miền Trung',
    phone: '0989012345',
    email: 'vani9@gmail.com',
    country: 'Việt Nam',
    city: 'Đà Nẵng',
    ward: 'Thanh Khê',
    address: '101 Nguyễn Tất Thành',
    avatarUrl: '',
  },
  {
    id: 10,
    fullName: 'Nguyen Thi K',
    dob: '1996-07-07',
    gender: 'Nữ',
    region: 'Miền Bắc',
    phone: '0990123456',
    email: 'thik10@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Đống Đa',
    address: '33 Chùa Láng',
    avatarUrl: '',
  },
  {
    id: 11,
    fullName: 'Tran Van L',
    dob: '1989-01-19',
    gender: 'Nam',
    region: 'Miền Nam',
    phone: '0901111111',
    email: 'vanl11@gmail.com',
    country: 'Việt Nam',
    city: 'TP.HCM',
    ward: 'Quận 7',
    address: 'Khu Phú Mỹ Hưng',
    avatarUrl: '',
  },
  {
    id: 12,
    fullName: 'Le Thi M',
    dob: '2000-10-10',
    gender: 'Nữ',
    region: 'Miền Trung',
    phone: '0912222222',
    email: 'thim12@gmail.com',
    country: 'Việt Nam',
    city: 'Quảng Nam',
    ward: 'Tam Kỳ',
    address: '12 Lê Lợi',
    avatarUrl: '',
  },
  {
    id: 13,
    fullName: 'Pham Van N',
    dob: '1993-03-03',
    gender: 'Nam',
    region: 'Miền Bắc',
    phone: '0923333333',
    email: 'vann13@gmail.com',
    country: 'Việt Nam',
    city: 'Bắc Ninh',
    ward: 'Từ Sơn',
    address: '56 Lý Thái Tổ',
    avatarUrl: '',
  },
  {
    id: 14,
    fullName: 'Vo Thi O',
    dob: '1997-09-09',
    gender: 'Nữ',
    region: 'Miền Nam',
    phone: '0934444444',
    email: 'thio14@gmail.com',
    country: 'Việt Nam',
    city: 'Vũng Tàu',
    ward: 'Phường 2',
    address: '88 Thùy Vân',
    avatarUrl: '',
  },
  {
    id: 15,
    fullName: 'Dang Van P',
    dob: '1995-05-05',
    gender: 'Nam',
    region: 'Miền Trung',
    phone: '0945555555',
    email: 'vanp15@gmail.com',
    country: 'Việt Nam',
    city: 'Nha Trang',
    ward: 'Lộc Thọ',
    address: '21 Trần Phú',
    avatarUrl: '',
  },
  {
    id: 16,
    fullName: 'Bui Thi Q',
    dob: '1998-08-08',
    gender: 'Nữ',
    region: 'Miền Bắc',
    phone: '0956666666',
    email: 'thiq16@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Hoàng Mai',
    address: '45 Giải Phóng',
    avatarUrl: '',
  },
  {
    id: 17,
    fullName: 'Do Van R',
    dob: '1991-11-11',
    gender: 'Nam',
    region: 'Miền Nam',
    phone: '0967777777',
    email: 'vanr17@gmail.com',
    country: 'Việt Nam',
    city: 'TP.HCM',
    ward: 'Quận 10',
    address: '99 Lý Thường Kiệt',
    avatarUrl: '',
  },
  {
    id: 18,
    fullName: 'Nguyen Thi S',
    dob: '1994-04-14',
    gender: 'Nữ',
    region: 'Miền Trung',
    phone: '0978888888',
    email: 'this18@gmail.com',
    country: 'Việt Nam',
    city: 'Đà Nẵng',
    ward: 'Sơn Trà',
    address: '12 Võ Nguyên Giáp',
    avatarUrl: '',
  },
  {
    id: 19,
    fullName: 'Tran Van T',
    dob: '1990-06-06',
    gender: 'Nam',
    region: 'Miền Bắc',
    phone: '0989999999',
    email: 'vant19@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Thanh Xuân',
    address: '67 Nguyễn Trãi',
    avatarUrl: '',
  },
  {
    id: 20,
    fullName: 'Le Thi U',
    dob: '1996-02-02',
    gender: 'Nữ',
    region: 'Miền Nam',
    phone: '0900000000',
    email: 'thiu20@gmail.com',
    country: 'Việt Nam',
    city: 'Cần Thơ',
    ward: 'Bình Thủy',
    address: '34 Cách Mạng Tháng 8',
    avatarUrl: '',
  },
  {
    id: 21,
    fullName: 'Pham Van V',
    dob: '1993-03-13',
    gender: 'Nam',
    region: 'Miền Trung',
    phone: '0911111112',
    email: 'vanv21@gmail.com',
    country: 'Việt Nam',
    city: 'Huế',
    ward: 'Phú Hội',
    address: '56 Lê Lợi',
    avatarUrl: '',
  },
  {
    id: 22,
    fullName: 'Vo Thi W',
    dob: '1997-07-17',
    gender: 'Nữ',
    region: 'Miền Bắc',
    phone: '0922222223',
    email: 'thiw22@gmail.com',
    country: 'Việt Nam',
    city: 'Hà Nội',
    ward: 'Tây Hồ',
    address: '12 Xuân Diệu',
    avatarUrl: '',
  },
  {
    id: 23,
    fullName: 'Dang Van X',
    dob: '1992-12-22',
    gender: 'Nam',
    region: 'Miền Nam',
    phone: '0933333334',
    email: 'vanx23@gmail.com',
    country: 'Việt Nam',
    city: 'TP.HCM',
    ward: 'Quận 5',
    address: '88 Trần Hưng Đạo',
    avatarUrl: '',
  },
  {
    id: 24,
    fullName: 'Bui Thi Y',
    dob: '1999-09-19',
    gender: 'Nữ',
    region: 'Miền Trung',
    phone: '0944444445',
    email: 'thiy24@gmail.com',
    country: 'Việt Nam',
    city: 'Quảng Ngãi',
    ward: 'TP Quảng Ngãi',
    address: '21 Nguyễn Nghiêm',
    avatarUrl: '',
  },
  {
    id: 25,
    fullName: 'Do Van Z',
    dob: '1991-01-01',
    gender: 'Nam',
    region: 'Miền Bắc',
    phone: '0955555556',
    email: 'vanz25@gmail.com',
    country: 'Việt Nam',
    city: 'Nam Định',
    ward: 'Trần Hưng Đạo',
    address: '45 Điện Biên',
    avatarUrl: '',
  },
  {
    id: 26,
    fullName: 'Nguyen Thi AA',
    dob: '1998-06-26',
    gender: 'Nữ',
    region: 'Miền Nam',
    phone: '0966666667',
    email: 'thiaa26@gmail.com',
    country: 'Việt Nam',
    city: 'Long An',
    ward: 'Tân An',
    address: '78 Hùng Vương',
    avatarUrl: '',
  },
  {
    id: 27,
    fullName: 'Tran Van BB',
    dob: '1994-04-24',
    gender: 'Nam',
    region: 'Miền Trung',
    phone: '0977777778',
    email: 'vanbb27@gmail.com',
    country: 'Việt Nam',
    city: 'Phú Yên',
    ward: 'Tuy Hòa',
    address: '12 Lê Duẩn',
    avatarUrl: '',
  },
  {
    id: 28,
    fullName: 'Le Thi CC',
    dob: '1996-03-16',
    gender: 'Nữ',
    region: 'Miền Bắc',
    phone: '0988888889',
    email: 'thicc28@gmail.com',
    country: 'Việt Nam',
    city: 'Thái Bình',
    ward: 'TP Thái Bình',
    address: '56 Trần Thái Tông',
    avatarUrl: '',
  },
  {
    id: 29,
    fullName: 'Pham Van DD',
    dob: '1992-02-12',
    gender: 'Nam',
    region: 'Miền Nam',
    phone: '0999999990',
    email: 'vandd29@gmail.com',
    country: 'Việt Nam',
    city: 'Bình Dương',
    ward: 'Thủ Dầu Một',
    address: '89 Đại lộ Bình Dương',
    avatarUrl: '',
  },
  {
    id: 30,
    fullName: 'Vo Thi EE',
    dob: '1995-10-20',
    gender: 'Nữ',
    region: 'Miền Trung',
    phone: '0901231231',
    email: 'thiee30@gmail.com',
    country: 'Việt Nam',
    city: 'Gia Lai',
    ward: 'Pleiku',
    address: '23 Nguyễn Tất Thành',
    avatarUrl: '',
  },
]
export default dataCandidate
